# Global settings applied to the whole site.
#
# “base” is the directory to change to before starting build. If you set base:
#        that is where we will look for package.json/.nvmrc/etc, not repo root!
# “command” is your build command.
# “publish” is the directory to publish (relative to the root of your repo).

[build]
  command = "yarn build"
  publish = "build"

[[headers]]
# Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' data: worker-src:; script-src https://ajax.cloudflare.com; style-src 'unsafe-inline' *.cloudfront.net; script-src-elem https://ajax.cloudflare.com https://www.googletagmanager.com https://*.cloudfront.net 'unsafe-inline'"
    X-Content-Security-Policy = "default-src 'self' data: worker-src:; script-src https://ajax.cloudflare.com; style-src 'unsafe-inline' *.cloudfront.net; script-src-elem https://ajax.cloudflare.com https://www.googletagmanager.com https://*.cloudfront.net 'unsafe-inline'"
    X-WebKit-CSP = "default-src 'self' data: worker-src:; script-src https://ajax.cloudflare.com; style-src 'unsafe-inline' *.cloudfront.net; script-src-elem https://ajax.cloudflare.com https://www.googletagmanager.com https://*.cloudfront.net 'unsafe-inline'"

